kind: Deployment
apiVersion: apps/v1
metadata:
  name: cam2ip
  namespace: default
  labels:
    app: cam2ip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cam2ip
  template:
    metadata:
      labels:
        app: cam2ip
    spec:
      nodeSelector:
        live-demo-container: "true"
      containers:
        - name: cam2ip
          image: gen2brain/cam2ip
          imagePullPolicy: Always
          ports:
            - containerPort: 56000
          volumeMounts:
            - name: dev
              mountPath: /dev
          securityContext:
            privileged: true
      volumes:
        - name: dev
          hostPath:
            path: /dev

---

apiVersion: v1
kind: Service
metadata:
  name: cam2ip
  namespace: default
  labels:
    app: cam2ip
spec:
  type: NodePort
  selector:
    app: cam2ip
  ports:
    - protocol: TCP
      port: 56000
      nodePort: 30001
      targetPort: 56000